networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./bot
    env_file:
      - BOT_TOKEN=${BOT_TOKEN}
      - PORT=${PORT}
    networks:
      - dev
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - BASE_URL=${BASE_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_API_KEY=${VITE_SUPABASE_API_KEY}
      - VITE_WALLET_ADDRESS=${VITE_WALLET_ADDRESS}
      - VITE_TONCENTER_URL=${VITE_TONCENTER_URL}
      - VITE_HOT_WALLET=${VITE_HOT_WALLET}
      - VITE_TONCENTER_API_KEY=${VITE_TONCENTER_API_KEY}
    networks:
      - dev
