networks:
  dev:

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - './nginx/static:/usr/share/nginx/html:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    stop_grace_period: 30s

  backend:
    build:
      context: ./bot
    env_file:
      - .env
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    networks:
      - dev