networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./bot
    networks:
      - dev
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
