networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./bot
    env_file:
      - .env
    networks:
      - dev
    ports:
      - "8000:8000"