networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './nginx/static/tonconnect-manifest.json:/usr/share/nginx/html/tonconnect-manifest.json:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./bot
    env_file:
      - .env
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    networks:
      - dev